// Package master implements the cleaner-facing Telegram bot.
//
// Masters join via /start invite_<token> link generated by the CRM. After
// activation they can:
//   - receive new-order notifications and Accept / Decline them
//   - mark accepted orders as Started / Completed
//   - toggle availability with /pause and /resume
package master

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/go-telegram/bot"
	"github.com/go-telegram/bot/models"
	"github.com/google/uuid"
	"github.com/sumatoha/kmf/backend/internal/bots/shared"
	botmodel "github.com/sumatoha/kmf/backend/internal/model"
	"github.com/sumatoha/kmf/backend/internal/service"
	"github.com/sumatoha/kmf/backend/internal/storage"
)

const invitePrefix = "invite_"

type Bot struct {
	b        *bot.Bot
	sessions *shared.Sessions
	tenants  *storage.TenantRepo
	masters  *service.MasterService
	mastersR *storage.MasterRepo
	orders   *service.OrderService
	ordersR  *storage.OrderRepo
	services *storage.ServiceRepo
	log      *slog.Logger
}

func New(
	token string,
	sessionsRepo *storage.SessionRepo,
	tenants *storage.TenantRepo,
	masters *service.MasterService,
	mastersR *storage.MasterRepo,
	orders *service.OrderService,
	ordersR *storage.OrderRepo,
	services *storage.ServiceRepo,
	log *slog.Logger,
) (*Bot, error) {
	mb := &Bot{
		sessions: shared.NewSessions(sessionsRepo, botmodel.BotKindMaster),
		tenants:  tenants,
		masters:  masters,
		mastersR: mastersR,
		orders:   orders,
		ordersR:  ordersR,
		services: services,
		log:      log,
	}
	b, err := bot.New(token, bot.WithDefaultHandler(mb.defaultHandler))
	if err != nil {
		return nil, fmt.Errorf("init master bot: %w", err)
	}
	mb.b = b

	b.RegisterHandler(bot.HandlerTypeMessageText, "/start", bot.MatchTypePrefix, mb.startHandler)
	b.RegisterHandler(bot.HandlerTypeMessageText, "/orders", bot.MatchTypeExact, mb.ordersHandler)
	b.RegisterHandler(bot.HandlerTypeMessageText, "/pause", bot.MatchTypeExact, mb.pauseHandler)
	b.RegisterHandler(bot.HandlerTypeMessageText, "/resume", bot.MatchTypeExact, mb.resumeHandler)
	b.RegisterHandler(bot.HandlerTypeCallbackQueryData, "ord:", bot.MatchTypePrefix, mb.callbackOrder)

	return mb, nil
}

func (m *Bot) Start(ctx context.Context) { m.b.Start(ctx) }

func (m *Bot) SendMessage(ctx context.Context, p *bot.SendMessageParams) (*models.Message, error) {
	return m.b.SendMessage(ctx, p)
}

func (m *Bot) defaultHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	if u.Message == nil {
		return
	}
	_, _ = b.SendMessage(ctx, &bot.SendMessageParams{
		ChatID: u.Message.Chat.ID,
		Text:   "Команды: /orders — мои заказы, /pause — приостановить приём, /resume — возобновить.",
	})
}

func (m *Bot) startHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	if u.Message == nil || u.Message.From == nil {
		return
	}
	chatID := u.Message.Chat.ID
	from := u.Message.From
	args := strings.TrimSpace(strings.TrimPrefix(u.Message.Text, "/start"))

	if strings.HasPrefix(args, invitePrefix) {
		token := strings.TrimPrefix(args, invitePrefix)
		var unPtr *string
		if from.Username != "" {
			u := from.Username
			unPtr = &u
		}
		master, err := m.masters.ActivateByInvite(ctx, token, from.ID, unPtr)
		if err != nil {
			_, _ = b.SendMessage(ctx, &bot.SendMessageParams{
				ChatID: chatID, Text: "Ссылка недействительна или уже использована.",
			})
			return
		}
		snap, _ := m.sessions.Load(ctx, chatID)
		snap.TenantID = &master.TenantID
		snap.State = "ready"
		_ = m.sessions.Save(ctx, chatID, snap)
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{
			ChatID: chatID,
			Text: fmt.Sprintf(
				"Добро пожаловать, %s!\nВы активированы как мастер. Новые заказы будут приходить сюда.\nКоманды: /orders, /pause, /resume.",
				master.FullName,
			),
		})
		return
	}

	// Existing master
	if _, err := m.masters.GetByTelegram(ctx, from.ID); err == nil {
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "С возвращением! /orders — текущие заказы."})
		return
	}
	_, _ = b.SendMessage(ctx, &bot.SendMessageParams{
		ChatID: chatID,
		Text:   "Чтобы войти, используйте пригласительную ссылку от вашей компании.",
	})
}

func (m *Bot) pauseHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	master, err := m.masters.GetByTelegram(ctx, u.Message.From.ID)
	if err != nil {
		return
	}
	_ = m.masters.SetAvailability(ctx, master.ID, false)
	_, _ = b.SendMessage(ctx, &bot.SendMessageParams{
		ChatID: u.Message.Chat.ID, Text: "Приём заказов приостановлен. /resume чтобы возобновить.",
	})
}

func (m *Bot) resumeHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	master, err := m.masters.GetByTelegram(ctx, u.Message.From.ID)
	if err != nil {
		return
	}
	_ = m.masters.SetAvailability(ctx, master.ID, true)
	_, _ = b.SendMessage(ctx, &bot.SendMessageParams{
		ChatID: u.Message.Chat.ID, Text: "Готов принимать заказы.",
	})
}

func (m *Bot) ordersHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	chatID := u.Message.Chat.ID
	master, err := m.masters.GetByTelegram(ctx, u.Message.From.ID)
	if err != nil {
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Сначала активируйтесь по пригласительной ссылке."})
		return
	}
	orders, err := m.ordersR.ListActiveForMaster(ctx, master.ID)
	if err != nil || len(orders) == 0 {
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Активных заказов нет."})
		return
	}
	for _, o := range orders {
		text := fmt.Sprintf(
			"Заказ #%s\nКогда: %s\nАдрес: %s\nСтатус: %s\nСтоимость: %.0f ₽",
			short(o.ID.String()), o.ScheduledAt.Format("02.01 15:04"), o.AddressText, o.Status, o.Price,
		)
		var rows [][]models.InlineKeyboardButton
		switch o.Status {
		case botmodel.OrderStatusConfirmed:
			rows = [][]models.InlineKeyboardButton{{
				{Text: "▶️ Начать", CallbackData: fmt.Sprintf("ord:start:%s", o.ID)},
			}}
		case botmodel.OrderStatusInProgress:
			rows = [][]models.InlineKeyboardButton{{
				{Text: "✅ Завершить", CallbackData: fmt.Sprintf("ord:done:%s", o.ID)},
			}}
		}
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{
			ChatID: chatID, Text: text,
			ReplyMarkup: &models.InlineKeyboardMarkup{InlineKeyboard: rows},
		})
	}
}

// callbackOrder handles ord:<action>:<id> callbacks.
func (m *Bot) callbackOrder(ctx context.Context, b *bot.Bot, u *models.Update) {
	cq := u.CallbackQuery
	if cq == nil {
		return
	}
	chatID := cq.Message.Message.Chat.ID
	_, _ = b.AnswerCallbackQuery(ctx, &bot.AnswerCallbackQueryParams{CallbackQueryID: cq.ID})

	parts := strings.Split(cq.Data, ":")
	if len(parts) != 3 {
		return
	}
	action := parts[1]
	orderID, err := uuid.Parse(parts[2])
	if err != nil {
		return
	}
	master, err := m.masters.GetByTelegram(ctx, cq.From.ID)
	if err != nil {
		return
	}

	switch action {
	case "accept":
		_, err := m.orders.AcceptByMaster(ctx, orderID, master.ID)
		if err != nil {
			if errors.Is(err, service.ErrInvalidState) {
				_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Заказ уже взят другим мастером."})
				return
			}
			m.log.Error("accept order", "err", err)
			return
		}
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Заказ принят. Удачной работы!"})

	case "decline":
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Ок, заказ показан другим мастерам."})

	case "start":
		if _, err := m.orders.Start(ctx, orderID, master.ID); err != nil {
			_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Не удалось начать заказ."})
			return
		}
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Уборка начата."})

	case "done":
		if _, err := m.orders.Complete(ctx, orderID, master.ID); err != nil {
			_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Не удалось завершить заказ."})
			return
		}
		_, _ = b.SendMessage(ctx, &bot.SendMessageParams{ChatID: chatID, Text: "Заказ завершён. Спасибо!"})
	}
}

func short(id string) string {
	if len(id) > 8 {
		return id[:8]
	}
	return id
}
