// Package master implements the cleaner-facing Telegram bot.
//
// Masters join via /start invite_<token> link generated by the CRM. After
// activation they can:
//   - receive new-order notifications and Accept / Decline them
//   - mark accepted orders as Started / Completed
//   - toggle availability with /pause and /resume
package master

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/go-telegram/bot"
	"github.com/go-telegram/bot/models"
	"github.com/google/uuid"
	"github.com/sumatoha/kmf/backend/internal/bots/shared"
	botmodel "github.com/sumatoha/kmf/backend/internal/model"
	"github.com/sumatoha/kmf/backend/internal/service"
	"github.com/sumatoha/kmf/backend/internal/storage"
)

const invitePrefix = "invite_"

type Bot struct {
	b        *bot.Bot
	sessions *shared.Sessions
	tenants  *storage.TenantRepo
	masters  *service.MasterService
	mastersR *storage.MasterRepo
	orders   *service.OrderService
	ordersR  *storage.OrderRepo
	services *storage.ServiceRepo
	log      *slog.Logger
}

type Deps struct {
	Token    string
	Sessions *storage.SessionRepo
	Tenants  *storage.TenantRepo
	Masters  *service.MasterService
	MastersR *storage.MasterRepo
	Orders   *service.OrderService
	OrdersR  *storage.OrderRepo
	Services *storage.ServiceRepo
	Log      *slog.Logger
}

func New(d Deps) (*Bot, error) {
	mb := &Bot{
		sessions: shared.NewSessions(d.Sessions, botmodel.BotKindMaster),
		tenants:  d.Tenants,
		masters:  d.Masters,
		mastersR: d.MastersR,
		orders:   d.Orders,
		ordersR:  d.OrdersR,
		services: d.Services,
		log:      d.Log,
	}
	b, err := bot.New(d.Token, bot.WithDefaultHandler(mb.defaultHandler))
	if err != nil {
		return nil, fmt.Errorf("init master bot: %w", err)
	}
	mb.b = b

	b.RegisterHandler(bot.HandlerTypeMessageText, "/start", bot.MatchTypePrefix, mb.startHandler)
	b.RegisterHandler(bot.HandlerTypeMessageText, "/orders", bot.MatchTypeExact, mb.ordersHandler)
	b.RegisterHandler(bot.HandlerTypeMessageText, "/pause", bot.MatchTypeExact, mb.pauseHandler)
	b.RegisterHandler(bot.HandlerTypeMessageText, "/resume", bot.MatchTypeExact, mb.resumeHandler)
	b.RegisterHandler(bot.HandlerTypeMessageText, "/help", bot.MatchTypeExact, mb.helpHandler)
	b.RegisterHandler(bot.HandlerTypeCallbackQueryData, "ord:", bot.MatchTypePrefix, mb.callbackOrder)

	return mb, nil
}

func (m *Bot) Start(ctx context.Context) { m.b.Start(ctx) }

func (m *Bot) Sender() shared.Sender { return m.b }
func (m *Bot) Logger() *slog.Logger  { return m.log }

func (m *Bot) defaultHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	if u.Message == nil {
		return
	}
	shared.Send(ctx, m.log, b, &bot.SendMessageParams{
		ChatID: u.Message.Chat.ID,
		Text:   "Команды: /orders — мои заказы, /pause — приостановить приём, /resume — возобновить.",
	})
}

func (m *Bot) helpHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	shared.Send(ctx, m.log, b, &bot.SendMessageParams{
		ChatID: u.Message.Chat.ID,
		Text: "Команды:\n/orders — мои заказы\n/pause — приостановить приём заказов\n/resume — возобновить",
	})
}

func (m *Bot) startHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	if u.Message == nil || u.Message.From == nil {
		return
	}
	chatID := u.Message.Chat.ID
	from := u.Message.From
	args := strings.TrimSpace(strings.TrimPrefix(u.Message.Text, "/start"))

	if strings.HasPrefix(args, invitePrefix) {
		token := strings.TrimPrefix(args, invitePrefix)
		var unPtr *string
		if from.Username != "" {
			u := from.Username
			unPtr = &u
		}
		master, err := m.masters.ActivateByInvite(ctx, token, from.ID, unPtr)
		if err != nil {
			m.log.Info("invite activation failed", "tg_id", from.ID, "err", err)
			shared.Send(ctx, m.log, b, &bot.SendMessageParams{
				ChatID: chatID, Text: "Ссылка недействительна или уже использована.",
			})
			return
		}
		snap, err := m.sessions.Load(ctx, chatID)
		if err != nil {
			m.log.Error("load session", "chat_id", chatID, "err", err)
			return
		}
		snap.TenantID = &master.TenantID
		snap.State = "ready"
		if err := m.sessions.Save(ctx, chatID, snap); err != nil {
			m.log.Error("save session", "chat_id", chatID, "err", err)
		}
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{
			ChatID: chatID,
			Text: fmt.Sprintf(
				"Добро пожаловать, %s!\nВы активированы как мастер. Новые заказы будут приходить сюда.\nКоманды: /orders, /pause, /resume.",
				master.FullName,
			),
		})
		return
	}

	if _, err := m.masters.GetByTelegram(ctx, from.ID); err == nil {
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "С возвращением! /orders — текущие заказы."})
		return
	}
	shared.Send(ctx, m.log, b, &bot.SendMessageParams{
		ChatID: chatID, Text: "Чтобы войти, используйте пригласительную ссылку от вашей компании.",
	})
}

func (m *Bot) pauseHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	master, err := m.masters.GetByTelegram(ctx, u.Message.From.ID)
	if err != nil {
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: u.Message.Chat.ID, Text: "Сначала активируйтесь по пригласительной ссылке."})
		return
	}
	if err := m.masters.SetAvailability(ctx, master.ID, false); err != nil {
		m.log.Error("set availability", "master_id", master.ID, "err", err)
	}
	shared.Send(ctx, m.log, b, &bot.SendMessageParams{
		ChatID: u.Message.Chat.ID, Text: "Приём заказов приостановлен. /resume чтобы возобновить.",
	})
}

func (m *Bot) resumeHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	master, err := m.masters.GetByTelegram(ctx, u.Message.From.ID)
	if err != nil {
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: u.Message.Chat.ID, Text: "Сначала активируйтесь по пригласительной ссылке."})
		return
	}
	if err := m.masters.SetAvailability(ctx, master.ID, true); err != nil {
		m.log.Error("set availability", "master_id", master.ID, "err", err)
	}
	shared.Send(ctx, m.log, b, &bot.SendMessageParams{
		ChatID: u.Message.Chat.ID, Text: "Готов принимать заказы.",
	})
}

func (m *Bot) ordersHandler(ctx context.Context, b *bot.Bot, u *models.Update) {
	chatID := u.Message.Chat.ID
	master, err := m.masters.GetByTelegram(ctx, u.Message.From.ID)
	if err != nil {
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Сначала активируйтесь по пригласительной ссылке."})
		return
	}
	orders, err := m.ordersR.ListActiveForMaster(ctx, master.ID)
	if err != nil {
		m.log.Error("list orders", "master_id", master.ID, "err", err)
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Не удалось загрузить заказы."})
		return
	}
	if len(orders) == 0 {
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Активных заказов нет."})
		return
	}
	for _, o := range orders {
		text := fmt.Sprintf(
			"Заказ #%s\nКогда: %s\nАдрес: %s\nСтатус: %s\nСтоимость: %.0f ₽",
			Short(o.ID.String()), o.ScheduledAt.Format("02.01 15:04"), o.AddressText, o.Status, o.Price,
		)
		var rows [][]models.InlineKeyboardButton
		switch o.Status {
		case botmodel.OrderStatusAssigned, botmodel.OrderStatusConfirmed:
			rows = [][]models.InlineKeyboardButton{{
				{Text: "▶️ Начать", CallbackData: fmt.Sprintf("ord:start:%s", o.ID)},
			}}
		case botmodel.OrderStatusInProgress:
			rows = [][]models.InlineKeyboardButton{{
				{Text: "✅ Завершить", CallbackData: fmt.Sprintf("ord:done:%s", o.ID)},
			}}
		}
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{
			ChatID: chatID, Text: text,
			ReplyMarkup: &models.InlineKeyboardMarkup{InlineKeyboard: rows},
		})
	}
}

// callbackOrder handles ord:<action>:<id> callbacks.
func (m *Bot) callbackOrder(ctx context.Context, b *bot.Bot, u *models.Update) {
	cq := u.CallbackQuery
	if cq == nil {
		return
	}
	chatID := cq.Message.Message.Chat.ID
	shared.AnswerCB(ctx, m.log, b, cq.ID)

	parts := strings.Split(cq.Data, ":")
	if len(parts) != 3 {
		return
	}
	action := parts[1]
	orderID, err := uuid.Parse(parts[2])
	if err != nil {
		return
	}
	master, err := m.masters.GetByTelegram(ctx, cq.From.ID)
	if err != nil {
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Сначала активируйтесь по пригласительной ссылке."})
		return
	}

	switch action {
	case "accept":
		if _, err := m.orders.AcceptByMaster(ctx, orderID, master.ID); err != nil {
			if errors.Is(err, service.ErrInvalidState) {
				shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Заказ уже взят другим мастером."})
				return
			}
			m.log.Error("accept order", "order_id", orderID, "master_id", master.ID, "err", err)
			shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Не удалось принять заказ."})
			return
		}
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Заказ принят. Удачной работы!"})

	case "decline":
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Ок, заказ показан другим мастерам."})

	case "start":
		if _, err := m.orders.Start(ctx, orderID, master.ID); err != nil {
			if errors.Is(err, service.ErrInvalidState) {
				shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Этот заказ нельзя начать сейчас."})
				return
			}
			m.log.Error("start order", "order_id", orderID, "err", err)
			shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Не удалось начать заказ."})
			return
		}
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Уборка начата."})

	case "done":
		if _, err := m.orders.Complete(ctx, orderID, master.ID); err != nil {
			if errors.Is(err, service.ErrInvalidState) {
				shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Этот заказ уже не в работе."})
				return
			}
			m.log.Error("complete order", "order_id", orderID, "err", err)
			shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Не удалось завершить заказ."})
			return
		}
		shared.Send(ctx, m.log, b, &bot.SendMessageParams{ChatID: chatID, Text: "Заказ завершён. Спасибо!"})
	}
}

// Short returns the first 8 characters of an id for compact display.
func Short(id string) string {
	if len(id) > 8 {
		return id[:8]
	}
	return id
}
